general = {
    name = "[ m u t e ] AirPlay";
    initial_volume = 0.0;           // Start at 100% (0dB)
    ignore_volume_control = "yes";  // Force fixed volume for best quality
};

alsa = {
    output_device = "default";      // Use default audio device
    mixer_control_name = "Digital"; // Your DAC's Hardware Mixer Name
};
