######## /etc/upmpdcli.conf

#### Media Renderer parameters

## UPnP/AV services
upnpav = 1
avfriendlyname = [ m u t e ] DLNA

## OpenHome services
openhome = 0
#friendlyname = [ m u t e ] OpenHome
#ohproductroom = [ m u t e ]

## Renderer icon
iconpath = /usr/share/upmpdcli/mute_icon.png

#### MPD Connection
# mpdhost = localhost
# mpdport = 6600
mpdtimeoutms = 2000
ownqueue = 1

#### Audio control hooks
externalvolumecontrol = 1
getexternalvolume = echo 100
